### ISSUE TITLE
没有办法配置dify，根本没有这个选项。是不是代码遗漏了

### ISSUE THREAD

**Issue by bjfk2006** [wan-h/awesome-digital-human-live2d#10]
![image](https://github.com/user-attachments/assets/27ee919f-2f38-4968-af52-4537fecc3af8)
代码部署和docker方式都是不行

**Comment by wan-h** [comment]
你的页面应该显示Soul is Death，你的server没有通，看一下readme中常见问题对于该问题的排查思路
