### ISSUE TITLE
localhost打不开

### ISSUE THREAD

**Issue by vvki123** [wan-h/awesome-digital-human-live2d#11]
部署后，日志也显示成功了，为什么localhost 3000端口打不开啊
![image](https://github.com/user-attachments/assets/43c735d1-a31e-426d-ba82-1dd94aea894e)

**Comment by wan-h** [comment]
你的windows系统吗

**Comment by vvki123** [comment]
是的





------------------ 原始邮件 ------------------
发件人: wan-h ***@***.***&gt;
发送时间: 2024年8月26日 13:54
收件人: wan-h/awesome-digital-human-live2d ***@***.***&gt;
抄送: vvki123 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [wan-h/awesome-digital-human-live2d] localhost打不开 (Issue #11)





 
你的windows系统吗

**Comment by vvki123** [comment]
我是通过docker部署的，然后宿主机打不开，日志也没啥报错





------------------ 原始邮件 ------------------
发件人: wan-h ***@***.***&gt;
发送时间: 2024年8月26日 13:54
收件人: wan-h/awesome-digital-human-live2d ***@***.***&gt;
抄送: vvki123 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [wan-h/awesome-digital-human-live2d] localhost打不开 (Issue #11)





 
你的windows系统吗

**Comment by wan-h** [comment]
readme中的常见问题更新了windows docker部署，参考一下
