### ISSUE TITLE
浏览器打开麦克风失败

### ISSUE THREAD

**Issue by cnsdytzy** [wan-h/awesome-digital-human-live2d#12]
按照视频教程已经配置了具有tts和speech2text功能的大模型，麦克风设备正常并授予相应应用使用权限，但是在点击麦克风语音输入时显示错误，“浏览器打开麦克风失败”。

**Comment by wan-h** [comment]
应该还是你浏览器得设置问题，检查一下浏览器访问其他语音输入得网站是否可以使用正常，看一下页面设置中权限是否正确：
![mic](https://github.com/user-attachments/assets/665e6365-281e-4168-a9cc-2d2314e7b7f6)

**Comment by Jerryqjr** [comment]
如果谷歌浏览器中无法获取麦克风权限可以使用谷歌的实验性功能：
chrome://flags/#unsafely-treat-insecure-origin-as-secure
![1724721445478](https://github.com/user-attachments/assets/9645197a-5814-48a6-acdf-629838c47faa)
此时会发现禁用的麦克风权限可选取，不过我在配置本地项目不存在这个问题。
当项目在服务器中部署后还未上线时，需要启用改功能临时解决跨域问题。

**Comment by wan-h** [comment]
是的，http才需要这个设置，https是不需要的

**Comment by cnsdytzy** [comment]
谢谢，已解决
