### ISSUE TITLE
请问数字人模式，回答就是重复问题是什么原因呢？也没有转成语音？

### ISSUE THREAD

**Issue by sunyclj** [wan-h/awesome-digital-human-live2d#13]
![image](https://github.com/user-attachments/assets/e178b677-2f5e-48fc-9d9b-2ee4377c6943)

**Comment by Jerryqjr** [comment]
Setting中服务选择DifyAgent
![image](https://github.com/user-attachments/assets/6bd39e30-4f65-408f-997c-484a10dc267a)

**Comment by wan-h** [comment]
默认ReapterAgent， 配置Dify的，或则现在支持了Fastgpt, 或则自己集成一个Agent
