### ISSUE TITLE
是否可以支持超真实的虚拟人?

### ISSUE THREAD

**Issue by jivaklong** [wan-h/awesome-digital-human-live2d#18]
是否支持真实虚拟人? 如何自定义超真实的虚拟人呢?
比如做一些导游、政务、商场需要一些虚拟人做场景更真实一些

**Comment by wan-h** [comment]
超写实的需要一些引擎驱动，目前只支持live2d的人物，如果是Live2d的人物集成按照readme中的开发指南操作即可
