### ISSUE TITLE
和difyAgent链接的问题

### ISSUE THREAD

**Issue by JerrZhang** [wan-h/awesome-digital-human-live2d#19]
在DifyAgent中设置了语音输出是日文，在dify中调试可以正常发音，但是在adh前端发音有问题，无法读出日文内容

**Comment by wan-h** [comment]
用的那个供应商以及人物选择，我本地调试看看，另外中文可以正常发音吗？

**Comment by JerrZhang** [comment]
中文可以正常发音，但是音色没有同步设置的内容（比如指定音色后不生效）

**Comment by wan-h** [comment]
你用的语音人物和语言发一下，我测试是没有问题的

**Comment by wan-h** [comment]
你用的语音人物和语言发一下，我测试是没有问题的

**Comment by wan-h** [comment]
No reply for more than 5 days, closed
