### ISSUE TITLE
soul is death

### ISSUE THREAD

**Issue by ignore1999** [wan-h/awesome-digital-human-live2d#2]
运行`docker-compose up -d`成功，并且http://{部署服务器IP}:3000 可以访问，但是告警soul is death。

**Comment by da-cai-ji** [comment]
+1，请问你解决了吗

**Comment by wan-h** [comment]
后端接口暴露在8000， soul is death表示后端心跳包没有接收到，检查一下后端是否启动以及是否可以访问

**Comment by ignore1999** [comment]
> 后端接口暴露在8000， soul is death表示后端心跳包没有接收到，检查一下后端是否启动以及是否可以访问

已解决，是后端端口的开放问题。

**Comment by turndown** [comment]
> > 后端接口暴露在8000， soul is death表示后端心跳包没有接收到，检查一下后端是否启动以及是否可以访问
> 
> 已解决，是后端端口的开放问题。

你好，请问要开放怎么样的权限？
我用8000端口失败了，以为是常用端口的问题，于是我把config文件和docker-compose文件的server启动端口改成5000，也将服务器的5000端口权限开放，docker服务也都是启动了，但是web打开还是报soul is death。
web服务：
![image](https://github.com/user-attachments/assets/b9c2b7a4-bf69-4f29-8133-a9c700d7b502)
server服务：

**Comment by turndown** [comment]
> > > 后端接口暴露在8000， soul is death表示后端心跳包没有接收到，检查一下后端是否启动以及是否可以访问
> > 
> > 
> > 已解决，是后端端口的开放问题。
> 
> 你好，请问要开放怎么样的权限？ 我用8000端口失败了，以为是常用端口的问题，于是我把config文件和docker-compose文件的server启动端口改成5000，也将服务器的5000端口权限开放，docker服务也都是启动了，但是web打开还是报soul is death。 web服务： ![image](https://private-user-images.githubusercontent.com/57825084/371978760-b9c2b7a4-bf69-4f29-8133-a9c700d7b502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODEyOTcsIm5iZiI6MTcyNzY4MDk5NywicGF0aCI6Ii81NzgyNTA4NC8zNzE5Nzg3NjAtYjljMmI3YTQtYmY2OS00ZjI5LTgxMzMtYTljNzAwZDdiNTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA3MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYWUxZGQyZDFiNWZlMDliMjIzOGQ3YjM3MTczYmJiYzY2MTdjOTgwY2JiNTM3YmZjMjExMjA5NjMyNzg2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tN7d0EVceGrUVr3Q2cjojd7cXlwoLPJBPiS6sFs_OzU) server服务： ![image](https://private-user-images.githubusercontent.com/57825084/371980330-915766eb-fcf0-4cec-94da-03bfc69042a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODEyOTcsIm5iZiI6MTcyNzY4MDk5NywicGF0aCI6Ii81NzgyNTA4NC8zNzE5ODAzMzAtOTE1NzY2ZWItZmNmMC00Y2VjLTk0ZGEtMDNiZmM2OTA0MmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA3MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMDgxOTVlNGQ0ZmM5MTljYzYwMWQxNmVhY2EwMDAyZjJkNjE3NzM5YzUyYzdmMDY4NGYxNjRkNTY4MThhYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SA1WDonljkiYdLhPNFMszqqxHt8J4hY43vyrfmqEmyQ) ![image](https://private-user-images.githubusercontent.com/57825084/371980230-086493fe-ea77-4eed-a5b2-1eedb7dfe528.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODEyOTcsIm5iZiI6MTcyNzY4MDk5NywicGF0aCI6Ii81NzgyNTA4NC8zNzE5ODAyMzAtMDg2NDkzZmUtZWE3Ny00ZWVkLWE1YjItMWVlZGI3ZGZlNTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA3MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNmZkYjJkMTA2YmRkOGQxYTAzNGVmNjQ2NTcxMTc3NzZhNjY3N2U2MDY1OGFhZjQxOTk2MDg4MWFiOGRkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5wQABgKVFRg4_z1r6hJDwZGxSWG_bYIMWQUchsLA2z8)

找到问题了，前端运行环境还要改下端口：
![image](https://github.com/user-attachments/assets/2e34659c-986b-42ac-9e10-ed44da42e35a)
