### ISSUE TITLE
根据b站视频配置之后无法使用

### ISSUE THREAD

**Issue by qkd90** [wan-h/awesome-digital-human-live2d#20]
![image](https://github.com/user-attachments/assets/a04acbf1-a1ef-42df-8eaa-e8803d858632)
根据视频教程配好了这两个地址，dify最近版本，但是无法回答问题

**Comment by wan-h** [comment]
后端日志有什么报错

**Comment by wan-h** [comment]
No reply for more than 5 days, closed
