### ISSUE TITLE
语音无法切换

### ISSUE THREAD

**Issue by 00wsmart00** [wan-h/awesome-digital-human-live2d#23]
链接到dify后，dify已经设置了语音了，但是数字人的声音回复还是默认的人声（数字人本身自带的声音），这是什么原因呢

**Comment by wan-h** [comment]
dify的应用切换后要点击更新

**Comment by wan-h** [comment]
1. 你是不是用的 all_in_dify这个配置文件
2. dify你切换语音之后要点击一下应用的更新
