### ISSUE TITLE
web/.env貌似不生效

### ISSUE THREAD

**Issue by thomasdba** [wan-h/awesome-digital-human-live2d#24]
<img width="978" alt="image" src="https://github.com/user-attachments/assets/ce41418e-675c-4207-b5ba-48bdeb10f2fc">
web/.env如下：

NEXT_PUBLIC_ADH_SERVER_IP="http://192.168.3.96"
NEXT_PUBLIC_ADH_SERVER_PORT="18000"
NEXT_PUBLIC_ADH_SERVER_VERSION="v0"

感觉这个env文件不生效啊，从浏览器的debug信息来看，他一直用的是默认的，还有这个IP变量，后面接着的url，但还不是完整的，不如用一个url变量代替host与Port的拼接。

**Comment by thomasdba** [comment]
/workspace # cat .env 
# https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables
# NEXT_PUBLIC_ADH_SERVER_IP="http://127.0.0.1"
NEXT_PUBLIC_ADH_SERVER_IP="http://192.168.3.96"
NEXT_PUBLIC_ADH_SERVER_PORT="18000"
NEXT_PUBLIC_ADH_SERVER_VERSION="v0"

在容器中已经看貌似也没有问题

**Comment by wan-h** [comment]
如果用的容器部署的话，用开发容器重新打包下就可

**Comment by wan-h** [comment]
url变量代替host与Port的拼接可以的，后面升级下
