### ISSUE TITLE
麦克风输入后页面卡死

### ISSUE THREAD

**Issue by KSamue1** [wan-h/awesome-digital-human-live2d#32]
麦克风输入后页面直接卡死，重新刷新页面后便一直提示soul is death，重新启动容器后恢复正常

**Comment by wan-h** [comment]
贴一下麦克风输入后卡死的server容器日志信息呢

**Comment by wan-h** [comment]
贴一下麦克风输入后卡死的server容器日志信息呢

**Comment by KSamue1** [comment]
看了日志已经解决了 国内服务器没有挂代理 访问不了google asr的问题 谢谢
