### ISSUE TITLE
web/.env后端端口没有效果,前端依旧访问8000

### ISSUE THREAD

**Issue by SAnBlog** [wan-h/awesome-digital-human-live2d#34]
# NEXT_PUBLIC_ADH_SERVER_IP="127.0.0.1"
NEXT_PUBLIC_ADH_SERVER_PROTOCOL="http"
NEXT_PUBLIC_ADH_SERVER_PORT="8006"
NEXT_PUBLIC_ADH_SERVER_VERSION="v0"

即使修改,容器内也成功同步,重启重新构建都无法请求到8006端口,请求到默认8000端口了

**Comment by SAnBlog** [comment]
mac是有什么限制吗?后端容器启动成功怎么都访问不了api,重新编译修改端口也没用,locahost,127.0.0.1都尝试过

**Comment by SAnBlog** [comment]
后端端口问题解决了,对话的时候dify成功接受到请求,日志里也查到回复了,但是前端一直显示 我想想

**Comment by wan-h** [comment]
拉最新的代码，做了一个fix，如果还是有问题贴一下你的后端日志

**Comment by radioend** [comment]
> 拉最新的代码，做了一个fix，如果还是有问题贴一下你的后端日志

您好，我无论本地，还是服务器跑。都是提示dify接口请求错误。 但语音又是正常的。还能播报：“dify接口请求错误”

错误日志：
[ERROR]2024-09-23 15:21:45,817 File 'difyAgent.py',line 49: [AGENT] Engine create conversation failed: Missing parameter: DIFY_API_URL
Traceback (most recent call last):
  File "/workspace/digitalHuman/agent/core/difyAgent.py", line 27, in createConversation
    raise RuntimeError(f"Missing parameter: {paramter['NAME']}")
RuntimeError: Missing parameter: DIFY_API_URL
INFO:     127.0.0.1:50440 - "POST /adh/agent/v0/conversation_id HTTP/1.1" 200 OK
[ERROR]2024-09-23 15:22:12,506 File 'difyAgent.py',line 49: [AGENT] Engine create conversation failed: Missing parameter: DIFY_API_URL
Traceback (most recent call last):
  File "/workspace/digitalHuman/agent/core/difyAgent.py", line 27, in createConversation
    raise RuntimeError(f"Missing parameter: {paramter['NAME']}")
RuntimeError: Missing parameter: DIFY_API_URL
INFO:     127.0.0.1:54334 - "POST /adh/agent/v0/conversation_id HTTP/1.1" 200 OK
INFO:     127.0.0.1:59924 - "POST /adh/agent/v0/infer HTTP/1.1" 200 OK
[ERROR]2024-09-23 15:22:24,060 File 'difyAgent.py',line 111: [AGENT] Engine run failed: Missing parameter: DIFY_API_URL
Traceback (most recent call last):
  File "/workspace/digitalHuman/agent/core/difyAgent.py", line 64, in run
    raise RuntimeError(f"Missing parameter: {paramter['NAME']}")
RuntimeError: Missing parameter: DIFY_API_URL
[DEBUG]2024-09-23 15:22:24,085 File 'difyTTS.py',line 42: [TTS] Engine input: dify接口请求返回错误。
INFO:     127.0.0.1:59924 - "POST /adh/tts/v0/infer HTTP/1.1" 200 OK

**Comment by wan-h** [comment]
1. 前端页面填写了dify API吗
2. 如果浏览器使用过之前版本的前端清理下页面的缓存

**Comment by SAnBlog** [comment]
NEXT_PUBLIC_ADH_SERVER_IP="本地IP或者域名"
NEXT_PUBLIC_ADH_SERVER_PROTOCOL="http/https"
NEXT_PUBLIC_ADH_SERVER_PORT="8000/443"
NEXT_PUBLIC_ADH_SERVER_VERSION="v0"  如果使用域名访问要注意配置,问题已解决
