### ISSUE TITLE
[Docker构建问题] 遇到“failed to solve: failed to register layer: max depth exceeded”错误

### ISSUE THREAD

**Issue by kellan04** [wan-h/awesome-digital-human-live2d#39]
**描述：**

我在尝试构建adhServer的Docker镜像时遇到了一个错误。错误信息表明超出了最大深度限制，我理解这与Docker镜像中的层数有关。我已经尝试使用`docker system prune -a`清理Docker环境，但问题仍然存在。有没有推荐的解决方法？

**错误信息：**
```
failed to solve: failed to register layer: max depth exceeded
```

**Dockerfile片段：**
```Dockerfile
# 可能导致问题的Dockerfile片段
# 使用阿里云镜像
FROM registry.cn-hangzhou.aliyuncs.com/awesome-digital-human/adh-api:main-latest
```

**环境：**
- Docker版本：26.1.3
- 操作系统：24.04 LTS (Noble Numbat)
- Docker存储驱动：
  Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false

**Comment by wan-h** [comment]
已经fix：28c596983f4e
