### ISSUE TITLE
内部错误，请检查dify信息

### ISSUE THREAD

**Issue by jhzqq2003** [wan-h/awesome-digital-human-live2d#4]
内部错误，请检查dify信息，确定信息是没错的。是哪个环节有问题吗？

**Comment by wan-h** [comment]
docker logs看一下你的server报错日志是什么

**Comment by jhzqq2003** [comment]
File 'difyAgent.py',line 80: [AGENT] Engine run failed

**Comment by wan-h** [comment]
拉最新的代码试试，会把具体报错信息打印出来，你这里本质原因是dify的接口请求问题

**Comment by jhzqq2003** [comment]
重新拉取main分支的V2.0.0依然不行哦

**Comment by wan-h** [comment]
如果有代码debug能力的话，可以看一下报错原因，try catch报错会返回这个信息：
![1724377381470](https://github.com/user-attachments/assets/381f3fc1-4adf-4558-9b64-9a4493782a31)

**Comment by LifeRainSunshine** [comment]
我也是这个问题  都是用docker安装的

**Comment by wan-h** [comment]
最新代码有添加了更详细的日志，看一下报错日志

**Comment by zhuhw19** [comment]
G:\awesome-digital-human-live2d\docker>docker compose up -d
time="2024-08-26T14:36:48+08:00" level=warning msg="G:\\awesome-digital-human-live2d\\docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.46/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Dawesome-digital-human-live2d%22%3Atrue%7D%7D": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.

**Comment by wan-h** [comment]
> G:\awesome-digital-human-live2d\docker>docker compose up -d time="2024-08-26T14:36:48+08:00" level=warning msg="G:\awesome-digital-human-live2d\docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion" error during connect: Get "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.46/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Dawesome-digital-human-live2d%22%3Atrue%7D%7D": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
镜像本地构建的时候报错吗，后面最一版更新，不用本地构建，镜像传到阿里云把

**Comment by wan-h** [comment]
已支持阿里云直接拉取镜像
