### ISSUE TITLE
为什么运行之后，能够回复，但是没有声音呢？

### ISSUE THREAD

**Issue by hal0n0sec** [wan-h/awesome-digital-human-live2d#41]
为什么运行之后，能够回复，但是没有声音呢？是在Windows 11 上运行的

**Comment by wan-h** [comment]
edge-tts最近官方服务挂了，你是用的什么tts

**Comment by wan-h** [comment]
贴一下server的报错日志瞧瞧

**Comment by gms5144** [comment]
我是用的通义千问的tts

**Comment by gms5144** [comment]
[ERROR]2024-11-05 01:54:53,539 File 'edgeTTS.py',line 50: [TTS] Engine run failed: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=48c49575aeca4caaa847c7ee86af5135'
Traceback (most recent call last):
  File "/workspace/digitalHuman/engine/tts/edgeTTS.py", line 36, in run
    async for message in communicate.stream():
  File "/usr/local/lib/python3.10/dist-packages/edge_tts/communicate.py", line 498, in stream
    async for message in self.__stream():
  File "/usr/local/lib/python3.10/dist-packages/edge_tts/communicate.py", line 365, in __stream
    async with aiohttp.ClientSession(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 953, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=48c49575aeca4caaa847c7ee86af5135'
[ERROR]2024-11-05 01:54:53,541 File 'reponse.py',line 41: TTS engine run failed

**Comment by gms5144** [comment]
已解决，切换成dify的tts后解决问题

**Comment by leoterry-ulrica** [comment]
> 已解决，切换成dify的tts后解决问题

请教具体怎么切换到dify的tts的？

**Comment by gms5144** [comment]
> > 已解决，切换成dify的tts后解决问题
> 
> 请教具体怎么切换到dify的tts的？
![1732774076283](https://github.com/user-attachments/assets/a2b4f357-a5da-4619-94a2-b150b2863f9f)
![1732774085990](https://github.com/user-attachments/assets/1f6b7907-6dc7-4aef-8347-b393c716cbf8)

**Comment by leoterry-ulrica** [comment]
> > > 已解决，切换成dify的tts后解决问题
> > 
> > 
> > 请教具体怎么切换到dify的tts的？
> > ![1732774076283](https://private-user-images.githubusercontent.com/91517592/390660311-a2b4f357-a5da-4619-94a2-b150b2863f9f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzQ0NTIsIm5iZiI6MTczMjc3NDE1MiwicGF0aCI6Ii85MTUxNzU5Mi8zOTA2NjAzMTEtYTJiNGYzNTctYTVkYS00NjE5LTk0YTItYjE1MGIyODYzZjlmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2MDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZDA3ZmE4Y2Q2N2ZiNjY2NTZhYzUwMTljZWNhNmQzYjU3NDgxYzhhMzEzOTMyYjFiMjg1YmNlZWFhMTExOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rqoaVMMthC74PWsL5-YLUKTShvCWK81Tn09_nOYyES4)
> > ![1732774085990](https://private-user-images.githubusercontent.com/91517592/390660327-1f6b7907-6dc7-4aef-8347-b393c716cbf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzQ0NTIsIm5iZiI6MTczMjc3NDE1MiwicGF0aCI6Ii85MTUxNzU5Mi8zOTA2NjAzMjctMWY2Yjc5MDctNmRjNy00YWVmLTgzNDctYjM5M2M3MTZjYmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2MDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OTFjY2RiODVkNDdmZTk2YjUxNTNlYzg1ZjVkOWJjZTY1OTBjOTc2ODVkNTk3MWVmM2Q1ZDM0OTU4NGY1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VdvqoXToCBpYqQRuivPuGFX9FjDb6Ng7ohKHXbVEACs)

谢谢，我试试！
