### ISSUE TITLE
edge_TTS使用代理后，docker的web服务老是重启

### ISSUE THREAD

**Issue by flyice8** [wan-h/awesome-digital-human-live2d#42]
TTS使用代理后，docker的web服务老是重启
在edge_tts上设置代理后，可以通过文字输入后获得语音输出，代理设置如下：
![image](https://github.com/user-attachments/assets/a30c0807-4c37-4d11-933f-24c4d9f3d392)

但是如果通过语音输入后，发现docker的web服务会重启。有如下错误信息
并web服务重启了一次
![image](https://github.com/user-attachments/assets/afddb9cf-aa69-4e93-aca9-b1957e486e33)

![image](https://github.com/user-attachments/assets/af4d9fdc-86ff-4004-8229-ea6f925b85ed)

**Comment by wan-h** [comment]
照理说web是没有啥影响的，看看你的3000端口是不是被其他占用了，一直在retry， 后端的这个问题是edge-tts最近国内无法访问了，见：https://github.com/rany2/edge-tts/issues/295
可以通富哦proxy指定本地代理端口，你这儿192.168.111.251改成 host.docker.internal 试试

**Comment by flyice8** [comment]
host.docker.internal 这样设置后,也不行了，看日志应该是没有代理，和之前的错误不一样，我用本地127.0.0.1也是最开始的状态
![image](https://github.com/user-attachments/assets/9326a033-5550-4c1e-a09f-a317dc777f8d)
![image](https://github.com/user-attachments/assets/78d2c08c-8369-45d7-b1c1-ada8f3be197b)

这个web的docker是确定不需要代理吗？我如果设置整台机器代理出去也就是服务器的网关设置为代理出去就是正常的

**Comment by flyice8** [comment]
这个感觉就是接收不行，googleASR.py不知道是不是也要设置代理，对话打文字是可以的，用语音就不行
ASR运行失败的状态
![image](https://github.com/user-attachments/assets/3c5ee6f6-047e-4b59-9eed-bd7b70a9abfd)

**Comment by wan-h** [comment]
如果你可以科学上网的话，开一个全局代理，这两个就都可以使用了，使用这个两个是因为免费，不过你也可以集成一下其他国内的接口

**Comment by wan-h** [comment]
tts最新版本已经fix
