### ISSUE TITLE
心跳的作用是什么?

### ISSUE THREAD

**Issue by SAnBlog** [wan-h/awesome-digital-human-live2d#47]
感觉心跳的机制不是很有必要啊,云服务器带宽速度很快的情况下也会经常超时报错,还是长连接,感觉挺耗资源的,心跳失败的情况下一样可以对话,对话也是会抛出错误

**Comment by wan-h** [comment]
心跳就是为了服务判活，有的同学后端没设置正常但是不知道什么情况，所有心跳包有一个判断依据，实际上确实可以不需要。

**Comment by wan-h** [comment]
超时报错的问题主要是因为使用dify-tts的时候会发生异步阻塞，这个近期会做fix

**Comment by SAnBlog** [comment]
> 超时报错的问题主要是因为使用dify-tts的时候会发生异步阻塞，这个近期会做fix

header.tsx文件去掉心跳相关的引入后,加载速度提高了很多,我觉得可以作为一个可配置引入比较好
