### ISSUE TITLE
conda构建环境，npm install遇到的问题

### ISSUE THREAD

**Issue by sunyclj** [wan-h/awesome-digital-human-live2d#8]
搭建环境的流程：
conda create -n awe python=3.10
conda activate awe
pip install -r requirements.txt
cd web
npm install
到这一步安装，就一直卡在(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠋ idealTree:web: sill idealTree buildDeps，两个小时都没进度，请问是什么原因呀？尝试换了镜像源也没用

**Comment by wan-h** [comment]
node用20+的版本试试，npm下载的东西并不多，检查一下你的node环境是否正常

**Comment by sunyclj** [comment]
> node用20+的版本试试，npm下载的东西并不多，检查一下你的node环境是否正常

已解决，node用22.6.0版本
