### ISSUE TITLE
希望支持自定义数字人

### ISSUE THREAD

**Issue by bestlee666** [wan-h/awesome-digital-human-live2d#9]
希望支持自定义数字人

**Comment by wan-h** [comment]
请看 https://github.com/wan-h/awesome-digital-human-live2d/blob/main/docs/developer_instrction.md 中的定制化开发

**Comment by wan-h** [comment]
请看 https://github.com/wan-h/awesome-digital-human-live2d/blob/main/docs/developer_instrction.md 中的定制化开发
